### ISSUE TITLE
Unable to store XMessage

### ISSUE THREAD

**Issue by ktwrd** [ktwrd/XeniaBot#13]
Ran into an issue when storing XMessage for tracking message changes

```
xenia-discord-prod-xenia-1  | [ERR]  [Discord->Gateway] System.InvalidOperationException: This property has no value set.
xenia-discord-prod-xenia-1  |    at XeniaBot.Data.Models.Archival.XMessageReference.FromMessageReference(MessageReference r) in /src/XeniaBot.Data/Models/Archival/XMessageModel.cs:line 207
xenia-discord-prod-xenia-1  |    at XeniaBot.Data.Models.Archival.XMessageModel.FromMessage(IMessage message) in /src/XeniaBot.Data/Models/Archival/XMessageModel.cs:line 66
xenia-discord-prod-xenia-1  |    at XeniaBot.Core.Controllers.Wrappers.ArchivalController._client_MessageReceived(SocketMessage message) in /src/XeniaBot.Core/Controllers/Wrappers/ArchivalController.cs:line 86
xenia-discord-prod-xenia-1  |    at Discord.EventExtensions.InvokeAsync[T](AsyncEvent`1 eventHandler, T arg)
xenia-discord-prod-xenia-1  |    at Discord.WebSocket.DiscordSocketClient.TimeoutWrap(String name, Func`1 action)
```

Issue is mainly with XMessageReference/CacheMessageReference

**Comment by ktwrd** [comment]
Unrelated note, there are also a lot of `Object reference not set to an instance of an object` in the `_client_UserUpdated` method of ArchivalController.

This is fixed already in `devel` branch

**Comment by ktwrd** [comment]
Issue was fixed by reimplementing *everything* that is used by `CacheMessageModel`.
